[phases.setup]
nixPkgs = ["nodejs-18_x", "php82"]

[phases.install]
cmds = [
  "npm install",
  "composer install --no-dev --optimize-autoloader"
]

[phases.build]
cmds = [
  "PUBLIC_URL=/ REACT_APP_API_BASE=/api npm run build"
]

[start]
cmd = "php -S 0.0.0.0:$PORT router.php"
